[phases.setup]
commands = [
  ""
]
aptPkgs = ["wget", "curl", "python3", "python3-pip", "python-is-python3", "libpq-dev", "python3-dev"]

[phases.build]
commands = [
  "pip3 install --upgrade build setuptools",
  "pip3 install -r requirements.txt"
]

[start]
cmd = 'python3 app.py'