[phases.setup]
commands = [
  ""
]
aptPkgs = ["wget", "curl", "python", "python-pip", "python-is-python2", "libpq-dev", "python-dev"]

[phases.build]
commands = [
  "pip install --upgrade build setuptools",
  "pip install -r requirements.txt"
]

[start]
cmd = 'python app.py'