[phases.setup]
commands = [
  ""
]
aptPkgs = ["wget", "curl", "python2", "python-pip", "libpq-dev", "python2-dev"]

[phases.build]
commands = [
  "pip install -r requirements.txt"
]

[start]
cmd = 'python2 app.py'